version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
        interval: 'weekly'
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"