name: CI
on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Node ${{ join(matrix.*, ' - ') }} - ${{ github.event_name }}
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Code style
      run: pnpm run lint
    - name: Build
      run: pnpm run build